services:
  nextjs:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ${GALLERY_PATH}:/app/public/gallery
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  cfnet:
    name: cfnet
    driver: bridge
    external: true
