name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Restart Docker Compose Service
        shell: powershell
        env:
          GALLERY_PATH: ${{ secrets.GALLERY_PATH }}
        run: |
          echo "Running docker compose command to rebuild and deploy..."
          docker compose -f docker-compose.yml up -d --build nextjs
          echo "Deployment completed."

      - name: Prune old Docker images
        shell: powershell
        if: always()
        run: |
          docker image prune -f
